DB_NAME=movie_api
DB_USERNAME=Fabian-Str
DB_PASSWORD=NTvnTx7!JHuBrYXsGNouTVroLxr.iB
DB_LINK=jdbc:postgresql://167.172.103.174:5432/
TMDB_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzNmU2NTcwNjdlMDA2OTNhNjc3NzRkNmEyODFiZDEyZiIsIm5iZiI6MTc4OTQ2NTI2Mi4wMzYsInN1YiI6IjZhYTkxMmFlOTcyNWZjZDA5NGMxOTBjOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.6iVwIlVORusW4sVmc8Y1EMCfoS8O8KqLATrP3tFb3f0
